version: '3.8'

volumes:
  postgres_data:
  static_value:
  media_value:
services:
  postgres:
    image: postgres:13.3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.prod/.postgres
  django:
    image: klyaxa/bbbs-backend:latest
    restart: always
    volumes:
      - static_value:/code/staticfiles/
      - media_value:/code/media
    depends_on:
      - postgres
    env_file:
      - ./.envs/.prod/.django
      - ./.envs/.prod/.postgres
  backend-nginx:
    image: nginx:1.21.0
    restart: always
    volumes:
      - ./nginx/backend/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - django
  public-nginx:
    image: klyaxa/bbbs-frontend:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/frontend/:/etc/nginx/conf.d/
