# версия docker-compose
version: '3.8'

volumes:
  postgres_data:
  static_value:

services:
  postgres:
    image: postgres:13.3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.prod/.postgres

  django:
    image: bbbs:v01.2021.06.13
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    restart: always
    volumes:
      - static_value:/code/staticfiles/
    depends_on:
      - postgres
    env_file:
      - ./.envs/.prod/.django
      - ./.envs/.prod/.postgres

  nginx:
    image: nginx:1.21.0
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - django
